<?php

return [
    'default_pair' => env('TRADING_DEFAULT_PAIR', 'XAUUSD'),

    /*
    |--------------------------------------------------------------------------
    | Supported Market Pairs
    |--------------------------------------------------------------------------
    |
    | Add or remove markets here. The key is the pair code used in query
    | strings (e.g. ?pair=EURUSD). Provider symbols are used by each market
    | data fallback source in TradingService.
    |
    */
    'pairs' => [
        'XAUUSD' => [
            'display' => 'XAU/USD',
            'name' => 'Gold Spot',
            'asset_class' => 'Metals',
            'twelvedata_symbol' => 'XAU/USD',
            'alpha_from_symbol' => 'XAU',
            'alpha_to_symbol' => 'USD',
            'yahoo_symbol' => 'GC=F',
            'pip_size' => 0.1,
        ],
        'EURUSD' => [
            'display' => 'EUR/USD',
            'name' => 'Euro / US Dollar',
            'asset_class' => 'FX Majors',
            'twelvedata_symbol' => 'EUR/USD',
            'alpha_from_symbol' => 'EUR',
            'alpha_to_symbol' => 'USD',
            'yahoo_symbol' => 'EURUSD=X',
            'pip_size' => 0.0001,
        ],
        'GBPUSD' => [
            'display' => 'GBP/USD',
            'name' => 'British Pound / US Dollar',
            'asset_class' => 'FX Majors',
            'twelvedata_symbol' => 'GBP/USD',
            'alpha_from_symbol' => 'GBP',
            'alpha_to_symbol' => 'USD',
            'yahoo_symbol' => 'GBPUSD=X',
            'pip_size' => 0.0001,
        ],
        'USDJPY' => [
            'display' => 'USD/JPY',
            'name' => 'US Dollar / Japanese Yen',
            'asset_class' => 'FX Majors',
            'twelvedata_symbol' => 'USD/JPY',
            'alpha_from_symbol' => 'USD',
            'alpha_to_symbol' => 'JPY',
            'yahoo_symbol' => 'USDJPY=X',
            'pip_size' => 0.01,
        ],
        'AUDUSD' => [
            'display' => 'AUD/USD',
            'name' => 'Australian Dollar / US Dollar',
            'asset_class' => 'FX Majors',
            'twelvedata_symbol' => 'AUD/USD',
            'alpha_from_symbol' => 'AUD',
            'alpha_to_symbol' => 'USD',
            'yahoo_symbol' => 'AUDUSD=X',
            'pip_size' => 0.0001,
        ],
        'USDCAD' => [
            'display' => 'USD/CAD',
            'name' => 'US Dollar / Canadian Dollar',
            'asset_class' => 'FX Majors',
            'twelvedata_symbol' => 'USD/CAD',
            'alpha_from_symbol' => 'USD',
            'alpha_to_symbol' => 'CAD',
            'yahoo_symbol' => 'USDCAD=X',
            'pip_size' => 0.0001,
        ],
        'USDCHF' => [
            'display' => 'USD/CHF',
            'name' => 'US Dollar / Swiss Franc',
            'asset_class' => 'FX Majors',
            'twelvedata_symbol' => 'USD/CHF',
            'alpha_from_symbol' => 'USD',
            'alpha_to_symbol' => 'CHF',
            'yahoo_symbol' => 'USDCHF=X',
            'pip_size' => 0.0001,
        ],
        'NZDUSD' => [
            'display' => 'NZD/USD',
            'name' => 'New Zealand Dollar / US Dollar',
            'asset_class' => 'FX Majors',
            'twelvedata_symbol' => 'NZD/USD',
            'alpha_from_symbol' => 'NZD',
            'alpha_to_symbol' => 'USD',
            'yahoo_symbol' => 'NZDUSD=X',
            'pip_size' => 0.0001,
        ],
        'EURGBP' => [
            'display' => 'EUR/GBP',
            'name' => 'Euro / British Pound',
            'asset_class' => 'FX Minors',
            'twelvedata_symbol' => 'EUR/GBP',
            'alpha_from_symbol' => 'EUR',
            'alpha_to_symbol' => 'GBP',
            'yahoo_symbol' => 'EURGBP=X',
            'pip_size' => 0.0001,
        ],
        'EURJPY' => [
            'display' => 'EUR/JPY',
            'name' => 'Euro / Japanese Yen',
            'asset_class' => 'FX Minors',
            'twelvedata_symbol' => 'EUR/JPY',
            'alpha_from_symbol' => 'EUR',
            'alpha_to_symbol' => 'JPY',
            'yahoo_symbol' => 'EURJPY=X',
            'pip_size' => 0.01,
        ],
        'EURCHF' => [
            'display' => 'EUR/CHF',
            'name' => 'Euro / Swiss Franc',
            'asset_class' => 'FX Minors',
            'twelvedata_symbol' => 'EUR/CHF',
            'alpha_from_symbol' => 'EUR',
            'alpha_to_symbol' => 'CHF',
            'yahoo_symbol' => 'EURCHF=X',
            'pip_size' => 0.0001,
        ],
        'EURAUD' => [
            'display' => 'EUR/AUD',
            'name' => 'Euro / Australian Dollar',
            'asset_class' => 'FX Minors',
            'twelvedata_symbol' => 'EUR/AUD',
            'alpha_from_symbol' => 'EUR',
            'alpha_to_symbol' => 'AUD',
            'yahoo_symbol' => 'EURAUD=X',
            'pip_size' => 0.0001,
        ],
        'EURNZD' => [
            'display' => 'EUR/NZD',
            'name' => 'Euro / New Zealand Dollar',
            'asset_class' => 'FX Minors',
            'twelvedata_symbol' => 'EUR/NZD',
            'alpha_from_symbol' => 'EUR',
            'alpha_to_symbol' => 'NZD',
            'yahoo_symbol' => 'EURNZD=X',
            'pip_size' => 0.0001,
        ],
        'EURCAD' => [
            'display' => 'EUR/CAD',
            'name' => 'Euro / Canadian Dollar',
            'asset_class' => 'FX Minors',
            'twelvedata_symbol' => 'EUR/CAD',
            'alpha_from_symbol' => 'EUR',
            'alpha_to_symbol' => 'CAD',
            'yahoo_symbol' => 'EURCAD=X',
            'pip_size' => 0.0001,
        ],
        'GBPJPY' => [
            'display' => 'GBP/JPY',
            'name' => 'British Pound / Japanese Yen',
            'asset_class' => 'FX Minors',
            'twelvedata_symbol' => 'GBP/JPY',
            'alpha_from_symbol' => 'GBP',
            'alpha_to_symbol' => 'JPY',
            'yahoo_symbol' => 'GBPJPY=X',
            'pip_size' => 0.01,
        ],
        'GBPCHF' => [
            'display' => 'GBP/CHF',
            'name' => 'British Pound / Swiss Franc',
            'asset_class' => 'FX Minors',
            'twelvedata_symbol' => 'GBP/CHF',
            'alpha_from_symbol' => 'GBP',
            'alpha_to_symbol' => 'CHF',
            'yahoo_symbol' => 'GBPCHF=X',
            'pip_size' => 0.0001,
        ],
        'GBPAUD' => [
            'display' => 'GBP/AUD',
            'name' => 'British Pound / Australian Dollar',
            'asset_class' => 'FX Minors',
            'twelvedata_symbol' => 'GBP/AUD',
            'alpha_from_symbol' => 'GBP',
            'alpha_to_symbol' => 'AUD',
            'yahoo_symbol' => 'GBPAUD=X',
            'pip_size' => 0.0001,
        ],
        'GBPNZD' => [
            'display' => 'GBP/NZD',
            'name' => 'British Pound / New Zealand Dollar',
            'asset_class' => 'FX Minors',
            'twelvedata_symbol' => 'GBP/NZD',
            'alpha_from_symbol' => 'GBP',
            'alpha_to_symbol' => 'NZD',
            'yahoo_symbol' => 'GBPNZD=X',
            'pip_size' => 0.0001,
        ],
        'GBPCAD' => [
            'display' => 'GBP/CAD',
            'name' => 'British Pound / Canadian Dollar',
            'asset_class' => 'FX Minors',
            'twelvedata_symbol' => 'GBP/CAD',
            'alpha_from_symbol' => 'GBP',
            'alpha_to_symbol' => 'CAD',
            'yahoo_symbol' => 'GBPCAD=X',
            'pip_size' => 0.0001,
        ],
        'AUDJPY' => [
            'display' => 'AUD/JPY',
            'name' => 'Australian Dollar / Japanese Yen',
            'asset_class' => 'FX Minors',
            'twelvedata_symbol' => 'AUD/JPY',
            'alpha_from_symbol' => 'AUD',
            'alpha_to_symbol' => 'JPY',
            'yahoo_symbol' => 'AUDJPY=X',
            'pip_size' => 0.01,
        ],
        'AUDNZD' => [
            'display' => 'AUD/NZD',
            'name' => 'Australian Dollar / New Zealand Dollar',
            'asset_class' => 'FX Minors',
            'twelvedata_symbol' => 'AUD/NZD',
            'alpha_from_symbol' => 'AUD',
            'alpha_to_symbol' => 'NZD',
            'yahoo_symbol' => 'AUDNZD=X',
            'pip_size' => 0.0001,
        ],
        'AUDCAD' => [
            'display' => 'AUD/CAD',
            'name' => 'Australian Dollar / Canadian Dollar',
            'asset_class' => 'FX Minors',
            'twelvedata_symbol' => 'AUD/CAD',
            'alpha_from_symbol' => 'AUD',
            'alpha_to_symbol' => 'CAD',
            'yahoo_symbol' => 'AUDCAD=X',
            'pip_size' => 0.0001,
        ],
        'AUDCHF' => [
            'display' => 'AUD/CHF',
            'name' => 'Australian Dollar / Swiss Franc',
            'asset_class' => 'FX Minors',
            'twelvedata_symbol' => 'AUD/CHF',
            'alpha_from_symbol' => 'AUD',
            'alpha_to_symbol' => 'CHF',
            'yahoo_symbol' => 'AUDCHF=X',
            'pip_size' => 0.0001,
        ],
        'NZDJPY' => [
            'display' => 'NZD/JPY',
            'name' => 'New Zealand Dollar / Japanese Yen',
            'asset_class' => 'FX Minors',
            'twelvedata_symbol' => 'NZD/JPY',
            'alpha_from_symbol' => 'NZD',
            'alpha_to_symbol' => 'JPY',
            'yahoo_symbol' => 'NZDJPY=X',
            'pip_size' => 0.01,
        ],
        'NZDCAD' => [
            'display' => 'NZD/CAD',
            'name' => 'New Zealand Dollar / Canadian Dollar',
            'asset_class' => 'FX Minors',
            'twelvedata_symbol' => 'NZD/CAD',
            'alpha_from_symbol' => 'NZD',
            'alpha_to_symbol' => 'CAD',
            'yahoo_symbol' => 'NZDCAD=X',
            'pip_size' => 0.0001,
        ],
        'NZDCHF' => [
            'display' => 'NZD/CHF',
            'name' => 'New Zealand Dollar / Swiss Franc',
            'asset_class' => 'FX Minors',
            'twelvedata_symbol' => 'NZD/CHF',
            'alpha_from_symbol' => 'NZD',
            'alpha_to_symbol' => 'CHF',
            'yahoo_symbol' => 'NZDCHF=X',
            'pip_size' => 0.0001,
        ],
        'CADJPY' => [
            'display' => 'CAD/JPY',
            'name' => 'Canadian Dollar / Japanese Yen',
            'asset_class' => 'FX Minors',
            'twelvedata_symbol' => 'CAD/JPY',
            'alpha_from_symbol' => 'CAD',
            'alpha_to_symbol' => 'JPY',
            'yahoo_symbol' => 'CADJPY=X',
            'pip_size' => 0.01,
        ],
        'CADCHF' => [
            'display' => 'CAD/CHF',
            'name' => 'Canadian Dollar / Swiss Franc',
            'asset_class' => 'FX Minors',
            'twelvedata_symbol' => 'CAD/CHF',
            'alpha_from_symbol' => 'CAD',
            'alpha_to_symbol' => 'CHF',
            'yahoo_symbol' => 'CADCHF=X',
            'pip_size' => 0.0001,
        ],
        'CHFJPY' => [
            'display' => 'CHF/JPY',
            'name' => 'Swiss Franc / Japanese Yen',
            'asset_class' => 'FX Minors',
            'twelvedata_symbol' => 'CHF/JPY',
            'alpha_from_symbol' => 'CHF',
            'alpha_to_symbol' => 'JPY',
            'yahoo_symbol' => 'CHFJPY=X',
            'pip_size' => 0.01,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Admin Matrix Throttling
    |--------------------------------------------------------------------------
    |
    | The all-pairs admin board can burst API calls. To stay below provider
    | minute limits, matrix reads cached snapshots and refreshes only a limited
    | number of pair-groups per request.
    |
    */
    'matrix' => [
        // Optional comma-separated codes, e.g. "XAUUSD,EURUSD,GBPUSD"
        'pair_codes' => env('TRADING_MATRIX_PAIRS', ''),
        // Snapshot cache TTL for matrix cells.
        'cache_seconds' => env('TRADING_MATRIX_CACHE_SECONDS', 900),
        // Max cold pairs to refresh per request (pair x all strategies).
        'refresh_pairs_per_request' => env('TRADING_MATRIX_REFRESH_PAIRS_PER_REQUEST', 1),
    ],

    'watchlist' => [
        // Default user watchlist if none saved yet.
        'default_pair_codes' => env('TRADING_WATCHLIST_DEFAULT_PAIRS', 'XAUUSD,EURUSD,GBPUSD,USDJPY'),
        // Hard cap to avoid overload and noisy UI.
        'max_pairs' => env('TRADING_WATCHLIST_MAX_PAIRS', 6),
        // Snapshot TTL for user watchlist cards.
        'cache_seconds' => env('TRADING_WATCHLIST_CACHE_SECONDS', 180),
    ],
];
